name: sample
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: step1
        run: |
          echo "Step-1"
      - name: printenv
        run: |
          printenv
      - name: step2
        run: |
          bash run.sh
          
        
        
        
