name: sample
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "Step-1"
      - name: step2
        run: |
          bash run.sh
          
        
        
        
