name: sample
on:
  pull_request:
    - main
  workflow_dispatch:
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: step1
      run: |
        echo "Step-1"
    - name: step2
      run: |
        bash run.sh
        
        
